export * from './About'
export * from './Main'
export * from './MvpVersion'
export * from './MainPage'
export * from './Bottom'
export * from './Services'
export * from './Objects'
export * from './Adaptation'